services:
  - type: web
    name: meal-management
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.8

databases:
  - name: mealmanagementdb
    plan: free
    databaseName: mealmanagement
    user: mealmanagement
